# Generated by Django 4.0.2 on 2022-02-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=2, verbose_name='Ubicación Actual')),
                ('fuel_km', models.FloatField(default=0, verbose_name='Consumo km/lt')),
                ('distance', models.IntegerField(default=1, verbose_name='Distancia recorrida')),
                ('fuel_consume', models.FloatField(default=0, verbose_name='Combustible consumido')),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['id'],
            },
        ),
    ]
